services:
  backend:
    build: ./backend
    container_name: vm_manager_backend
    restart: unless-stopped
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
      - VAGRANT_HOME=/home/iris/.vagrant.d
    volumes:
      - ./backend:/app
      - ./student_vms:/app/student_vms
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - /usr/bin/vagrant:/usr/bin/vagrant:ro
      - /opt/vagrant:/opt/vagrant:ro
      - /home/iris/.vagrant.d:/home/iris/.vagrant.d
    networks:
      - admin_proxy

  frontend:
    build: ./frontend
    container_name: vm_manager_frontend
    restart: unless-stopped
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=admin_proxy"
      - "traefik.http.routers.vm_manager.entrypoints=web"
      - "traefik.http.routers.vm_manager.rule=Host(`vm-manager.${DOMAIN_NAME}`)"
      - "traefik.http.routers.vm_manager.service=vm_manager"
      - "traefik.http.services.vm_manager.loadbalancer.server.port=80"
    networks:
      - admin_proxy

networks:
  admin_proxy:
    external: true
